%% lebesgue_random_chebyshev.m
%
% Computational experiment: Lebesgue constant for "random Chebyshev" nodes.
%
% This script investigates the growth of the Lebesgue constant when
% interpolation nodes are generated by projecting uniform random angles
% onto [-1, 1] via cosine. Specifically, if theta ~ Uniform(0, pi), then
% x = cos(theta) has the arcsine distribution, which naturally clusters
% points near the endpoints like Chebyshev nodes.
%
% Mathematical insight: If theta ~ Uniform(0, pi), then x = cos(theta) has PDF
%     f(x) = 1 / (pi * sqrt(1 - x^2))
% which is the arcsine distribution (Chebyshev weight function).
%
% Author: Dr. Denys Dutykh
%         Mathematics Department
%         Khalifa University of Science and Technology
%         Abu Dhabi, UAE
%
% Part of the book "Computational Etudes: A Spectral Approach"
%
% Created: February 2026

clear; close all; clc;

%% Configuration
N_FINE = 2000;          % Number of points for Lebesgue function evaluation
M_TRIALS = 200;         % Number of Monte Carlo trials per N
N_MAX = 30;             % Maximum polynomial degree
SEED = 42;              % Random seed for reproducibility

% Book color scheme
NAVY = [20, 45, 110] / 255;
SKY = [120, 150, 210] / 255;
CORAL = [231, 76, 60] / 255;
TEAL = [22, 160, 133] / 255;
GOLD = [243, 156, 18] / 255;      % Color for uniform random nodes
PURPLE = [155, 89, 182] / 255;    % New color for random Chebyshev nodes

% Output path
script_dir = fileparts(mfilename('fullpath'));
output_dir = fullfile(script_dir, '..', '..', '..', 'textbook', 'figures', 'ch04', 'matlab');
output_file = fullfile(output_dir, 'lebesgue_random_chebyshev.pdf');

%% Set random seed
rng(SEED);

%% Fine grid for Lebesgue function evaluation
x_fine = linspace(-1, 1, N_FINE)';

%% Initialize arrays
N_values = 2:N_MAX;
n_N = length(N_values);

% Statistics for random Chebyshev
Lambda_mean = zeros(n_N, 1);
Lambda_std = zeros(n_N, 1);
Lambda_min = zeros(n_N, 1);
Lambda_max = zeros(n_N, 1);
Lambda_median = zeros(n_N, 1);
Lambda_p25 = zeros(n_N, 1);
Lambda_p75 = zeros(n_N, 1);

% Comparison distributions
Lambda_equi = zeros(n_N, 1);
Lambda_cheb = zeros(n_N, 1);
Lambda_uniform_mean = zeros(n_N, 1);

%% Run Monte Carlo simulation
fprintf('=======================================================================\n');
fprintf('Computational Experiment: Lebesgue Constant for Random Chebyshev Nodes\n');
fprintf('=======================================================================\n\n');
fprintf('Nodes generated by projecting uniform random angles via cosine:\n');
fprintf('    theta ~ Uniform(0, pi)  -->  x = cos(theta)\n');
fprintf('This gives the arcsine distribution on [-1, 1].\n\n');
fprintf('Running Monte Carlo simulation with M = %d trials per N...\n', M_TRIALS);
fprintf('N ranges from 2 to %d\n\n', N_MAX);

for i = 1:n_N
    N = N_values(i);

    % Monte Carlo samples for random Chebyshev
    samples = zeros(M_TRIALS, 1);
    for m = 1:M_TRIALS
        theta = pi * rand(N+1, 1);        % Uniform on [0, pi]
        x_rand_cheb = sort(cos(theta));   % Project via cosine and sort
        samples(m) = max(lebesgue_function(x_rand_cheb, x_fine));
    end

    % Statistics
    Lambda_mean(i) = mean(samples);
    Lambda_std(i) = std(samples);
    Lambda_min(i) = min(samples);
    Lambda_max(i) = max(samples);
    Lambda_median(i) = median(samples);
    Lambda_p25(i) = prctile(samples, 25);
    Lambda_p75(i) = prctile(samples, 75);

    % Monte Carlo for uniform random (for comparison)
    samples_uniform = zeros(M_TRIALS, 1);
    for m = 1:M_TRIALS
        x_rand = sort(2 * rand(N+1, 1) - 1);  % Uniform on [-1, 1]
        samples_uniform(m) = max(lebesgue_function(x_rand, x_fine));
    end
    Lambda_uniform_mean(i) = mean(samples_uniform);

    % Deterministic distributions
    x_equi = linspace(-1, 1, N+1)';
    Lambda_equi(i) = max(lebesgue_function(x_equi, x_fine));

    j = 0:N;
    x_cheb = cos(j * pi / N)';
    Lambda_cheb(i) = max(lebesgue_function(x_cheb, x_fine));

    % Progress report
    if mod(i, 5) == 0 || N == N_MAX
        fprintf('  N = %2d: Lambda_mean = %10.4f, std = %8.4f, range = [%.2f, %.2f]\n', ...
                N, Lambda_mean(i), Lambda_std(i), Lambda_min(i), Lambda_max(i));
    end
end

%% Fit empirical formulas
fprintf('\n-----------------------------------------------------------------------\n');
fprintf('Fitting empirical asymptotic formulas...\n');

% Use data for N >= 5 to avoid small-N effects
mask = N_values >= 5;
N_fit_data = N_values(mask)';
Lambda_fit_data = Lambda_mean(mask);

% Exponential fit in log space: log(Lambda) = a + b*N
log_Lambda = log(Lambda_fit_data);
p_exp = polyfit(N_fit_data, log_Lambda, 1);
b_exp = p_exp(1);
a_exp = exp(p_exp(2));

% Logarithmic fit: Lambda = a + b*ln(N)
p_log = polyfit(log(N_fit_data), Lambda_fit_data, 1);
b_log = p_log(1);
a_log = p_log(2);

% Compute residuals for both models
Lambda_fit_exp = a_exp * exp(b_exp * N_fit_data);
Lambda_fit_log = a_log + b_log * log(N_fit_data);
resid_exp = sum((Lambda_fit_data - Lambda_fit_exp).^2);
resid_log = sum((Lambda_fit_data - Lambda_fit_log).^2);

fprintf('\nExponential model: Lambda_N ~ %.4f * exp(%.4f * N)\n', a_exp, b_exp);
fprintf('  Residual sum of squares: %.4e\n', resid_exp);

fprintf('\nLogarithmic model: Lambda_N ~ %.4f + %.4f * ln(N)\n', a_log, b_log);
fprintf('  Residual sum of squares: %.4e\n', resid_log);

% Determine best fit
if resid_log < resid_exp
    fprintf('\n*** Logarithmic model provides better fit! ***\n');
    use_log_fit = true;
else
    fprintf('\n*** Exponential model provides better fit ***\n');
    use_log_fit = false;
end

%% Create figure
fig = figure('Units', 'inches', 'Position', [1, 1, 11, 4.5]);

% -------------------------------------------------------------------------
% Left panel: Growth of Lebesgue constant with confidence bands
% -------------------------------------------------------------------------
subplot(1, 2, 1);
hold on; box on;
set(gca, 'YScale', 'log');  % Force logarithmic scale before fill()

% Shaded region for random Chebyshev nodes (min to max)
fill([N_values, fliplr(N_values)], [Lambda_min', fliplr(Lambda_max')], ...
     PURPLE, 'FaceAlpha', 0.2, 'EdgeColor', 'none', 'DisplayName', 'Random Chebyshev (min-max)');

% Shaded region for interquartile range
fill([N_values, fliplr(N_values)], [Lambda_p25', fliplr(Lambda_p75')], ...
     PURPLE, 'FaceAlpha', 0.3, 'EdgeColor', 'none', 'DisplayName', 'Random Chebyshev (IQR)');

% Mean line for random Chebyshev nodes
h1 = semilogy(N_values, Lambda_mean, 'o-', 'Color', PURPLE, 'LineWidth', 1.5, ...
              'MarkerSize', 4, 'DisplayName', 'Random Chebyshev (mean)');

% Uniform random for comparison
h2 = semilogy(N_values, Lambda_uniform_mean, 'd--', 'Color', GOLD, 'LineWidth', 1.2, ...
              'MarkerSize', 3, 'DisplayName', 'Uniform random (mean)');
h2.Color(4) = 0.7;

% Equispaced for comparison
h3 = semilogy(N_values, Lambda_equi, 's--', 'Color', CORAL, 'LineWidth', 1.2, ...
              'MarkerSize', 3, 'DisplayName', 'Equispaced');
h3.Color(4) = 0.7;

% Chebyshev for reference
h4 = semilogy(N_values, Lambda_cheb, '^--', 'Color', SKY, 'LineWidth', 1.2, ...
              'MarkerSize', 3, 'DisplayName', 'Chebyshev');
h4.Color(4) = 0.7;

% Fitted curve
N_curve = linspace(5, N_MAX, 100);
if use_log_fit
    Lambda_curve = a_log + b_log * log(N_curve);
    fit_label = sprintf('Fit: $\\Lambda_N \\sim %.2f + %.2f\\ln N$', a_log, b_log);
else
    Lambda_curve = a_exp * exp(b_exp * N_curve);
    fit_label = sprintf('Fit: $\\Lambda_N \\sim %.2f e^{%.3fN}$', a_exp, b_exp);
end
h5 = semilogy(N_curve, Lambda_curve, '-', 'Color', NAVY, 'LineWidth', 1.5, ...
              'DisplayName', fit_label);
h5.Color(4) = 0.8;

xlabel('$N$ (polynomial degree)', 'Interpreter', 'latex');
ylabel('Lebesgue constant $\Lambda_N$', 'Interpreter', 'latex');
title('Growth of Lebesgue Constant', 'FontSize', 11);
xlim([0, N_MAX + 2]);
legend([h1, h2, h3, h4, h5], {'Random Chebyshev (mean)', 'Uniform random (mean)', ...
        'Equispaced', 'Chebyshev', fit_label}, ...
       'Location', 'northwest', 'Interpreter', 'latex', 'FontSize', 7.5);

% Add text annotations
if use_log_fit
    text(N_MAX - 5, Lambda_mean(end) * 1.8, '$O(\ln N)$', ...
         'Interpreter', 'latex', 'FontSize', 10, 'Color', PURPLE);
else
    text(N_MAX - 5, Lambda_mean(end) * 1.8, '$O(e^{bN})$', ...
         'Interpreter', 'latex', 'FontSize', 10, 'Color', PURPLE);
end
text(N_MAX - 5, Lambda_cheb(end) * 1.5, '$O(\ln N)$', ...
     'Interpreter', 'latex', 'FontSize', 10, 'Color', SKY);

set(gca, 'FontSize', 10, 'TickLabelInterpreter', 'latex');
grid on;
set(gca, 'GridAlpha', 0.2);

% -------------------------------------------------------------------------
% Right panel: Distribution at fixed N (log-scale histogram)
% -------------------------------------------------------------------------
subplot(1, 2, 2);
hold on; box on;

N_hist = 15;
M_hist = 500;
samples_hist = zeros(M_hist, 1);
for m = 1:M_hist
    theta = pi * rand(N_hist+1, 1);
    x_rand_cheb = sort(cos(theta));
    samples_hist(m) = max(lebesgue_function(x_rand_cheb, x_fine));
end

% Compute statistics
mean_val = mean(samples_hist);
median_val = median(samples_hist);
equi_val = max(lebesgue_function(linspace(-1, 1, N_hist+1)', x_fine));
j = 0:N_hist;
cheb_val = max(lebesgue_function(cos(j * pi / N_hist)', x_fine));

% Use log-scale histogram to show the spread
log_samples = log10(samples_hist);

% Create histogram with log-spaced bins
bins = linspace(floor(min(log_samples)), ceil(max(log_samples)), 35);
histogram(log_samples, bins, 'FaceColor', PURPLE, 'FaceAlpha', 0.7, 'EdgeColor', 'white');

% Add vertical lines for statistics (on log scale)
xline(log10(median_val), '--', 'Color', TEAL, 'LineWidth', 2, ...
      'DisplayName', sprintf('Median = %.1f', median_val));
xline(log10(mean_val), '-', 'Color', NAVY, 'LineWidth', 2, ...
      'DisplayName', sprintf('Mean = %.1f', mean_val));
xline(log10(equi_val), ':', 'Color', CORAL, 'LineWidth', 2, ...
      'DisplayName', sprintf('Equispaced = $10^{%.1f}$', log10(equi_val)));
xline(log10(cheb_val), '-.', 'Color', SKY, 'LineWidth', 2, ...
      'DisplayName', sprintf('Chebyshev = %.1f', cheb_val));

xlabel('$\log_{10}(\Lambda_{15})$', 'Interpreter', 'latex');
ylabel('Count', 'Interpreter', 'latex');
title(sprintf('Distribution of $\\Lambda_N$ for $N = %d$ (%d trials)', N_hist, M_hist), ...
      'FontSize', 11, 'Interpreter', 'latex');
legend('Location', 'northeast', 'Interpreter', 'latex', 'FontSize', 8);

% Add annotation about the spread
spread = log10(max(samples_hist)) - log10(min(samples_hist));
text(0.05, 0.95, sprintf('Spread: %.1f orders\nof magnitude', spread), ...
     'Units', 'normalized', 'HorizontalAlignment', 'left', ...
     'VerticalAlignment', 'top', 'FontSize', 9, 'Interpreter', 'latex', ...
     'BackgroundColor', 'white');

set(gca, 'FontSize', 10, 'TickLabelInterpreter', 'latex');
grid on;
set(gca, 'GridAlpha', 0.2);

%% Save figure
if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

exportgraphics(fig, output_file, 'ContentType', 'vector');
fprintf('\nFigure saved to: %s\n', output_file);

png_file = strrep(output_file, '.pdf', '.png');
exportgraphics(fig, png_file, 'Resolution', 300);

%% Print summary table
fprintf('\n=======================================================================\n');
fprintf('Summary Statistics\n');
fprintf('=======================================================================\n');
fprintf('%4s %12s %12s %12s %10s\n', 'N', 'Rand-Cheb', 'Uniform', 'Equispaced', 'Chebyshev');
fprintf('-----------------------------------------------------------------------\n');
for i = 1:3:n_N
    N = N_values(i);
    fprintf('%4d %12.4f %12.4f %12.4f %10.4f\n', ...
            N, Lambda_mean(i), Lambda_uniform_mean(i), Lambda_equi(i), Lambda_cheb(i));
end
fprintf('-----------------------------------------------------------------------\n');

fprintf('\n=======================================================================\n');
fprintf('EMPIRICAL ASYMPTOTIC FORMULA\n');
fprintf('=======================================================================\n');
fprintf('\nFor random Chebyshev nodes (theta ~ Uniform(0, pi), x = cos(theta)):\n');

if use_log_fit
    fprintf('\n    Lambda_N ~ %.4f + %.4f * ln(N)\n', a_log, b_log);
    fprintf('\nThis is LOGARITHMIC growth, similar to Chebyshev nodes!\n');
    fprintf('The endpoint clustering induced by the arcsine distribution\n');
    fprintf('is the key property for stable interpolation.\n');
else
    fprintf('\n    Lambda_N ~ %.4f * exp(%.4f * N)\n', a_exp, b_exp);
    fprintf('\nor approximately:\n');
    fprintf('\n    Lambda_N ~ %.4f * %.4f^N\n', a_exp, exp(b_exp));
    fprintf('\nThe growth is slower than uniform random nodes.\n');
end
fprintf('=======================================================================\n');

%% Helper function: Lebesgue function
function Lambda = lebesgue_function(x_nodes, x_eval)
    N = length(x_nodes) - 1;
    Lambda = zeros(size(x_eval));

    for k = 1:N+1
        L_k = ones(size(x_eval));
        for j = 1:N+1
            if j ~= k
                L_k = L_k .* (x_eval - x_nodes(j)) / (x_nodes(k) - x_nodes(j));
            end
        end
        Lambda = Lambda + abs(L_k);
    end
end
