# lebesgue_random_chebyshev.jl
#
# Computational experiment: Lebesgue constant for "random Chebyshev" nodes.
#
# This script investigates the growth of the Lebesgue constant when interpolation
# nodes are generated by projecting uniform random angles onto [-1, 1] via cosine.
# Specifically, if theta ~ Uniform(0, pi), then x = cos(theta) has the arcsine
# distribution, which naturally clusters points near the endpoints like Chebyshev
# nodes.
#
# The experiment:
#     1. For each N, generate N+1 random angles uniformly on [0, pi]
#     2. Project to [-1, 1] via x = cos(theta)
#     3. Compute the Lebesgue constant for these nodes
#     4. Repeat M times to obtain statistics (mean, std, min, max)
#     5. Fit an empirical asymptotic formula to the averaged data
#
# Mathematical insight: If theta ~ Uniform(0, pi), then x = cos(theta) has PDF
#     f(x) = 1 / (pi * sqrt(1 - x^2))
# which is the arcsine distribution (Chebyshev weight function).
#
# Author: Dr. Denys Dutykh
#         Mathematics Department
#         Khalifa University of Science and Technology
#         Abu Dhabi, UAE
#
# Part of the book "Computational Etudes: A Spectral Approach"
# https://github.com/dutykh/computational-etudes

using CairoMakie
using Colors
using LaTeXStrings
using Random
using Statistics
using LsqFit

# -----------------------------------------------------------------------------
# Publication-quality CairoMakie configuration
# -----------------------------------------------------------------------------
set_theme!(Theme(
    fontsize = 11,
    fonts = (regular = "CMU Serif", bold = "CMU Serif Bold", italic = "CMU Serif Italic"),
    Axis = (xlabelsize = 11, ylabelsize = 11, titlesize = 12,
            xticklabelsize = 10, yticklabelsize = 10,
            spinewidth = 0.8, xtickwidth = 0.8, ytickwidth = 0.8),
    Legend = (labelsize = 10,),
))

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
const N_FINE = 2000       # Number of points for Lebesgue function evaluation
const M_TRIALS = 200      # Number of Monte Carlo trials per N
const N_MAX = 30          # Maximum polynomial degree
const SEED = 42           # Random seed for reproducibility

# Book color scheme
const NAVY   = colorant"#142D6E"
const SKY    = colorant"#7896D2"
const CORAL  = colorant"#E74C3C"
const TEAL   = colorant"#16A085"
const GOLD   = colorant"#F39C12"
const PURPLE = colorant"#9B59B6"

# Output path
const SCRIPT_DIR = @__DIR__
const OUTPUT_DIR = joinpath(SCRIPT_DIR, "..", "..", "..", "textbook", "figures", "ch04", "julia")

# -----------------------------------------------------------------------------
# Node generation
# -----------------------------------------------------------------------------
"""Generate N+1 'random Chebyshev' nodes by projecting uniform random angles."""
function random_chebyshev_nodes(N, rng)
    theta = rand(rng, N + 1) .* π
    return sort(cos.(theta))
end

"""Generate N+1 random nodes uniformly on [-1, 1] (for comparison)."""
random_nodes(N, rng) = sort(2.0 .* rand(rng, N + 1) .- 1.0)

"""Equispaced nodes on [-1, 1]."""
equispaced_nodes(N) = collect(range(-1, 1, length=N+1))

"""Chebyshev-Gauss-Lobatto nodes on [-1, 1]."""
chebyshev_nodes(N) = [cos(j * π / N) for j in 0:N]

# -----------------------------------------------------------------------------
# Lebesgue function computation
# -----------------------------------------------------------------------------
function lagrange_basis(x_nodes, k, x_eval)
    n = length(x_nodes)
    L_k = ones(length(x_eval))
    for j in 1:n
        if j != k
            L_k .*= (x_eval .- x_nodes[j]) ./ (x_nodes[k] - x_nodes[j])
        end
    end
    return L_k
end

function lebesgue_function(x_nodes, x_eval)
    N = length(x_nodes) - 1
    Lambda = zeros(length(x_eval))
    for k in 1:N+1
        Lambda .+= abs.(lagrange_basis(x_nodes, k, x_eval))
    end
    return Lambda
end

function lebesgue_constant(x_nodes; n_eval=2000)
    x_eval = collect(range(-1, 1, length=n_eval))
    Lambda = lebesgue_function(x_nodes, x_eval)
    return maximum(Lambda)
end

# -----------------------------------------------------------------------------
# Monte Carlo experiment
# -----------------------------------------------------------------------------
function monte_carlo_lebesgue(N, M, rng; n_eval=2000, node_type=:random_chebyshev)
    node_func = node_type == :random_chebyshev ? random_chebyshev_nodes : random_nodes
    samples = zeros(M)
    for m in 1:M
        x_rand = node_func(N, rng)
        samples[m] = lebesgue_constant(x_rand, n_eval=n_eval)
    end
    return samples
end

# -----------------------------------------------------------------------------
# Empirical fitting models
# -----------------------------------------------------------------------------
exponential_model(N, p) = p[1] .* exp.(p[2] .* N) ./ N .^ p[3]
logarithmic_model(N, p) = p[1] .+ p[2] .* log.(N)

# -----------------------------------------------------------------------------
# Main computation and visualization
# -----------------------------------------------------------------------------
function main()
    println("=" ^ 70)
    println("Computational Experiment: Lebesgue Constant for Random Chebyshev Nodes")
    println("=" ^ 70)
    println("\nNodes generated by projecting uniform random angles via cosine:")
    println("    theta ~ Uniform(0, pi)  -->  x = cos(theta)")
    println("This gives the arcsine distribution on [-1, 1].")

    rng = MersenneTwister(SEED)

    N_values = 2:N_MAX
    n_N = length(N_values)

    # Statistics arrays for random Chebyshev
    Lambda_mean   = zeros(n_N)
    Lambda_std    = zeros(n_N)
    Lambda_min    = zeros(n_N)
    Lambda_max    = zeros(n_N)
    Lambda_median = zeros(n_N)
    Lambda_p25    = zeros(n_N)
    Lambda_p75    = zeros(n_N)

    # Comparison distributions
    Lambda_equi         = zeros(n_N)
    Lambda_cheb         = zeros(n_N)
    Lambda_uniform_mean = zeros(n_N)

    println("\nRunning Monte Carlo simulation with M = $M_TRIALS trials per N...")
    println("N ranges from 2 to $N_MAX")
    println()

    for (i, N) in enumerate(N_values)
        # Monte Carlo for random Chebyshev nodes
        samples = monte_carlo_lebesgue(N, M_TRIALS, rng,
                                       n_eval=N_FINE, node_type=:random_chebyshev)

        Lambda_mean[i]   = mean(samples)
        Lambda_std[i]    = std(samples)
        Lambda_min[i]    = minimum(samples)
        Lambda_max[i]    = maximum(samples)
        Lambda_median[i] = median(samples)
        Lambda_p25[i]    = quantile(samples, 0.25)
        Lambda_p75[i]    = quantile(samples, 0.75)

        # Monte Carlo for uniform random (for comparison)
        samples_uniform = monte_carlo_lebesgue(N, M_TRIALS, rng,
                                               n_eval=N_FINE, node_type=:uniform)
        Lambda_uniform_mean[i] = mean(samples_uniform)

        # Deterministic distributions
        Lambda_equi[i] = lebesgue_constant(equispaced_nodes(N), n_eval=N_FINE)
        Lambda_cheb[i] = lebesgue_constant(chebyshev_nodes(N), n_eval=N_FINE)

        if (i % 5 == 0) || N == N_MAX
            println("  N = $(lpad(N, 2)): Lambda_mean = $(lpad(round(Lambda_mean[i], digits=4), 10)), " *
                    "std = $(lpad(round(Lambda_std[i], digits=4), 8)), " *
                    "range = [$(round(Lambda_min[i], digits=2)), $(round(Lambda_max[i], digits=2))]")
        end
    end

    # =========================================================================
    # Fit empirical formulas
    # =========================================================================
    println("\n" * "-" ^ 70)
    println("Fitting empirical asymptotic formulas...")

    mask = collect(N_values) .>= 5
    N_fit_data = Float64.(collect(N_values)[mask])
    Lambda_fit_data = Lambda_mean[mask]

    # --- Exponential model: Lambda ~ a * exp(b * N) / N^c ---
    p0_exp = [0.5, 0.1, 0.5]
    fit_exp = try
        curve_fit(exponential_model, N_fit_data, Lambda_fit_data, p0_exp; maxIter=10000)
    catch
        nothing
    end

    if fit_exp !== nothing
        a_exp, b_exp, c_exp = fit_exp.param
    else
        # Fallback: simple exponential fit in log space
        log_Lambda = log.(Lambda_fit_data)
        A = hcat(ones(length(N_fit_data)), N_fit_data)
        coeffs = A \ log_Lambda
        a_exp, b_exp, c_exp = exp(coeffs[1]), coeffs[2], 0.0
    end

    # --- Logarithmic model: Lambda ~ a + b * ln(N) ---
    p0_log = [1.0, 1.0]
    fit_log = try
        curve_fit(logarithmic_model, N_fit_data, Lambda_fit_data, p0_log; maxIter=10000)
    catch
        nothing
    end

    if fit_log !== nothing
        a_log, b_log = fit_log.param
    else
        # Fallback: direct linear regression on log(N)
        A = hcat(ones(length(N_fit_data)), log.(N_fit_data))
        coeffs = A \ Lambda_fit_data
        a_log, b_log = coeffs[1], coeffs[2]
    end

    # Compute residuals for both models
    Lambda_pred_exp = exponential_model(N_fit_data, [a_exp, b_exp, c_exp])
    Lambda_pred_log = logarithmic_model(N_fit_data, [a_log, b_log])
    resid_exp = sum((Lambda_fit_data .- Lambda_pred_exp).^2)
    resid_log = sum((Lambda_fit_data .- Lambda_pred_log).^2)

    println("\nExponential model: Lambda_N ~ $(round(a_exp, digits=4)) * exp($(round(b_exp, digits=4)) * N) / N^$(round(c_exp, digits=4))")
    println("  Residual sum of squares: $(round(resid_exp, sigdigits=4))")

    println("\nLogarithmic model: Lambda_N ~ $(round(a_log, digits=4)) + $(round(b_log, digits=4)) * ln(N)")
    println("  Residual sum of squares: $(round(resid_log, sigdigits=4))")

    use_log_fit = resid_log < resid_exp
    if use_log_fit
        println("\n*** Logarithmic model provides better fit! ***")
    else
        println("\n*** Exponential model provides better fit ***")
    end

    # =========================================================================
    # Create figure
    # =========================================================================
    fig = Figure(size = (1100, 450))

    # -------------------------------------------------------------------------
    # Left panel: Growth of Lebesgue constant with confidence bands
    # -------------------------------------------------------------------------
    ax1 = Axis(fig[1, 1],
               xlabel = L"N" * " (polynomial degree)",
               ylabel = L"\Lambda_N" * " (Lebesgue constant)",
               title = "Growth of Lebesgue Constant",
               limits = ((0, N_MAX + 2), nothing),
               yscale = log10)

    # Shaded regions for random Chebyshev nodes
    band!(ax1, collect(N_values), Lambda_min, Lambda_max,
          color = (PURPLE, 0.2), label = "Random Chebyshev (min-max)")
    band!(ax1, collect(N_values), Lambda_p25, Lambda_p75,
          color = (PURPLE, 0.3), label = "Random Chebyshev (IQR)")

    # Mean line for random Chebyshev nodes
    scatterlines!(ax1, collect(N_values), Lambda_mean, color = PURPLE,
                  linewidth = 1.5, markersize = 6, label = "Random Chebyshev (mean)")

    # Uniform random for comparison
    scatterlines!(ax1, collect(N_values), Lambda_uniform_mean, color = GOLD,
                  linewidth = 1.2, markersize = 5, marker = :diamond,
                  linestyle = :dash, label = "Uniform random (mean)")

    # Equispaced
    scatterlines!(ax1, collect(N_values), Lambda_equi, color = CORAL,
                  linewidth = 1.2, markersize = 5, marker = :rect,
                  linestyle = :dash, label = "Equispaced")

    # Chebyshev
    scatterlines!(ax1, collect(N_values), Lambda_cheb, color = SKY,
                  linewidth = 1.2, markersize = 5, marker = :utriangle,
                  linestyle = :dash, label = "Chebyshev")

    # Fitted curve
    N_fit_plot = collect(range(5, N_MAX, length=100))
    if use_log_fit
        Lambda_fit_plot = logarithmic_model(N_fit_plot, [a_log, b_log])
        fit_label = latexstring("Fit: \\Lambda_N \\sim $(round(a_log, digits=2)) + $(round(b_log, digits=2))\\ln N")
    else
        Lambda_fit_plot = exponential_model(N_fit_plot, [a_exp, b_exp, c_exp])
        fit_label = latexstring("Fit: \\Lambda_N \\sim $(round(a_exp, digits=2)) e^{$(round(b_exp, digits=3))N}")
    end
    lines!(ax1, N_fit_plot, Lambda_fit_plot, color = NAVY, linewidth = 1.5,
           label = fit_label)

    # Growth rate annotations
    if use_log_fit
        text!(ax1, N_MAX - 5, Lambda_mean[end] * 1.8, text = L"O(\ln N)",
              fontsize = 10, color = PURPLE)
    else
        text!(ax1, N_MAX - 5, Lambda_mean[end] * 1.8, text = L"O(e^{bN})",
              fontsize = 10, color = PURPLE)
    end
    text!(ax1, N_MAX - 5, Lambda_cheb[end] * 1.5, text = L"O(\ln N)",
          fontsize = 10, color = SKY)

    axislegend(ax1, position = :lt, framevisible = false, labelsize = 7.5)

    # -------------------------------------------------------------------------
    # Right panel: Distribution at fixed N (log-scale histogram)
    # -------------------------------------------------------------------------
    N_hist = 15
    M_hist = 500
    rng2 = MersenneTwister(SEED + 1)
    samples_hist = monte_carlo_lebesgue(N_hist, M_hist, rng2,
                                        n_eval=N_FINE, node_type=:random_chebyshev)

    mean_val   = mean(samples_hist)
    median_val = median(samples_hist)
    equi_val   = lebesgue_constant(equispaced_nodes(N_hist), n_eval=N_FINE)
    cheb_val   = lebesgue_constant(chebyshev_nodes(N_hist), n_eval=N_FINE)

    log_samples = log10.(samples_hist)

    ax2 = Axis(fig[1, 2],
               xlabel = L"\log_{10}(\Lambda_{15})",
               ylabel = "Count",
               title = "Distribution of \$\\Lambda_N\$ for N = $N_hist ($M_hist trials)")

    hist!(ax2, log_samples, bins = 35, color = (PURPLE, 0.7),
          strokecolor = :white, strokewidth = 0.5)

    # Vertical lines for statistics
    vlines!(ax2, log10(median_val), color = TEAL, linewidth = 2, linestyle = :dash,
            label = "Median = $(round(median_val, digits=1))")
    vlines!(ax2, log10(mean_val), color = NAVY, linewidth = 2,
            label = "Mean = $(round(mean_val, digits=1))")
    vlines!(ax2, log10(equi_val), color = CORAL, linewidth = 2, linestyle = :dot,
            label = latexstring("Equispaced = 10^{$(round(log10(equi_val), digits=1))}"))
    vlines!(ax2, log10(cheb_val), color = SKY, linewidth = 2, linestyle = :dashdot,
            label = "Chebyshev = $(round(cheb_val, digits=1))")

    # Spread annotation
    spread = log10(maximum(samples_hist)) - log10(minimum(samples_hist))
    text!(ax2, 0.05, 0.95, text = "Spread: $(round(spread, digits=1)) orders\nof magnitude",
          fontsize = 9, space = :relative, align = (:left, :top))

    axislegend(ax2, position = :rt, framevisible = false, labelsize = 8)

    # Save figure
    mkpath(OUTPUT_DIR)
    save(joinpath(OUTPUT_DIR, "lebesgue_random_chebyshev.pdf"), fig)
    save(joinpath(OUTPUT_DIR, "lebesgue_random_chebyshev.png"), fig, px_per_unit = 4)

    println("\nFigure saved to: ", joinpath(OUTPUT_DIR, "lebesgue_random_chebyshev.pdf"))

    # =========================================================================
    # Print summary table
    # =========================================================================
    println("\n" * "=" ^ 70)
    println("Summary Statistics")
    println("=" ^ 70)
    println("$(rpad("N", 4)) $(lpad("Rand-Cheb", 12)) $(lpad("Uniform", 12)) $(lpad("Equispaced", 12)) $(lpad("Chebyshev", 10))")
    println("-" ^ 70)
    for i in 1:3:n_N
        N = N_values[i]
        println("$(lpad(N, 4)) $(lpad(round(Lambda_mean[i], digits=4), 12)) " *
                "$(lpad(round(Lambda_uniform_mean[i], digits=4), 12)) " *
                "$(lpad(round(Lambda_equi[i], digits=4), 12)) " *
                "$(lpad(round(Lambda_cheb[i], digits=4), 10))")
    end
    println("-" ^ 70)

    println("\n" * "=" ^ 70)
    println("EMPIRICAL ASYMPTOTIC FORMULA")
    println("=" ^ 70)
    println("\nFor random Chebyshev nodes (theta ~ Uniform(0, pi), x = cos(theta)):")

    if use_log_fit
        println("\n    Lambda_N ~ $(round(a_log, digits=4)) + $(round(b_log, digits=4)) * ln(N)")
        println("\nThis is LOGARITHMIC growth, similar to Chebyshev nodes!")
        println("The endpoint clustering induced by the arcsine distribution")
        println("is the key property for stable interpolation.")
    else
        println("\n    Lambda_N ~ $(round(a_exp, digits=4)) * exp($(round(b_exp, digits=4)) * N) / N^$(round(c_exp, digits=4))")
        println("\nor approximately:")
        println("\n    Lambda_N ~ $(round(a_exp, digits=4)) * $(round(exp(b_exp), digits=4))^N")
        println("\nThe growth is slower than uniform random nodes.")
    end
    println("=" ^ 70)

    return fig
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
