// textbook/chapters/appendix_c_software.typ
// Appendix C: Software, Reproducibility, and the Repository
// Author: Dr. Denys Dutykh (Khalifa University, Abu Dhabi, UAE)
// Last modified: April 2026

#import "../styles/template.typ": dropcap

= Software, Reproducibility, and the Repository <appendix-software>

#dropcap[Every figure, table, and numerical statement in this volume was generated by code that lives alongside the manuscript in a single public repository.] This appendix is the operator's manual: it describes the repository layout, the per-language environment specifications that make the printed numbers exactly reproducible, and the GNU Make pipeline that re-renders the entire book --- 132 études, 150-odd figures, 30-odd tables, 700-odd pages of typeset text --- with a single shell command.

== Repository layout <appendix-software-layout>

The top-level structure of the repository is

```text
computational-etudes/
├── README.md
├── LICENSE                  (CC BY-NC-SA 4.0)
├── Makefile                 (build pipeline; ~3 300 lines)
├── pyproject.toml           (Python environment pin)
├── requirements.txt         (pip-friendly mirror of pyproject.toml)
├── Project.toml             (Julia environment pin)
├── Manifest.toml            (Julia full dependency lock)
├── assets/                  (cover art and supplementary illustrations)
├── codes/                   (the three-language source tree)
│   ├── README.md
│   ├── python/  ch02 ... ch21
│   ├── matlab/  ch02 ... ch21
│   └── julia/   ch02 ... ch21
├── textbook/
│   ├── main.typ             (entry point)
│   ├── chapters/            (21 chapter files + 4 appendices + frontmatter)
│   ├── styles/              (template.typ + bibliography style)
│   ├── biblio/library.bib
│   ├── figures/  ch02 ... ch21 / {python, matlab, julia}
│   └── build/               (compilation output, not committed)
├── slides/                  (lecture decks built from chapter material)
└── tplan/                   (a sample teaching plan)
```

Three navigational guarantees follow from this layout. First, every script in `codes/<language>/ch<NN>/` produces *exactly one* PDF figure, written to the matching `textbook/figures/ch<NN>/<language>/<basename>.pdf`. Second, every figure cited in the body refers to one of the three languages' versions of the same script; the three versions are *byte-equivalent up to font rendering*. Third, the Makefile's variable convention (`PY_CH<NN>`, `M_CH<NN>`, `JL_CH<NN>` for the directory names; `PY_SCRIPTS_CH<NN>` etc. for the script lists; `PY_FIGS_CH<NN>` etc. for the figure outputs) makes adding a chapter or a new étude a strictly mechanical edit.

== Setup by language <appendix-software-setup>

The repository ships pinned environment specifications for two of the three languages; the third (MATLAB) has no industry-standard analogue and is documented inline in this section.

=== Python (`pyproject.toml`, `requirements.txt`)

The Python pipeline is built on the standard scientific stack: NumPy for arrays and linear algebra, SciPy for special functions and quadrature, Matplotlib for figures, SymPy for the symbolic études of @ch-special-tricks. The `pyproject.toml` at the repository root pins the *exact* versions used at the time of typesetting (Python $gt.eq.slant$ 3.11; NumPy 2.2.4; SciPy 1.15.3; Matplotlib 3.10.1; SymPy 1.13.3); `requirements.txt` is a pip-friendly mirror.

To set up a fresh environment:

```bash
# Option A: pip + venv
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

# Option B: uv (if available)
uv pip sync requirements.txt

# Option C: Poetry / PDM
poetry install      # reads pyproject.toml directly
```

The symbolic études of @sec-st-symbolic ("Symbolic Spectral Methods") embed *exact rational coefficients* of secular determinants in the printed text. These coefficients depend on the SymPy version: a future SymPy release that changes its simplification heuristics may produce algebraically equivalent but textually different output. The `sympy` pin in `pyproject.toml` is therefore not a stylistic choice but a *correctness* requirement for verbatim reproduction of the printed numbers in Études 21.9, 21.10, and 21.11.

=== Julia (`Project.toml`, `Manifest.toml`)

The Julia pipeline uses FFTW.jl for fast Fourier transforms, FastGaussQuadrature.jl for Gauss-rule nodes and weights, SpecialFunctions.jl for Bessel and other transcendentals, LinearAlgebra (Julia stdlib) for the dense eigensolvers, and Symbolics.jl + SymPy.jl for the symbolic études. The `Project.toml` at the repository root declares *minimum* compatible versions via the `[compat]` section --- Julia 1.10 or 1.12, FFTW 1.10, FastGaussQuadrature 1.1, SpecialFunctions 2.5+, Symbolics 7.15, SymPy.jl 2.3 --- and a regenerated `Manifest.toml` records the *exact* resolved versions used at typesetting time.

To set up a fresh Julia environment:

```bash
cd /path/to/computational-etudes
julia --project=. -e 'using Pkg; Pkg.instantiate()'
```

Once instantiated, every Julia script in `codes/julia/` runs against the locked dependency graph:

```bash
julia --project=. codes/julia/ch20/truncation_stalls.jl
```

Activating the environment in the Julia REPL is the conventional alternative:

```julia
julia> using Pkg
julia> Pkg.activate(".")
julia> Pkg.instantiate()
julia> include("codes/julia/ch20/truncation_stalls.jl")
```

=== MATLAB

MATLAB has no equivalent of `Project.toml`. The printed output of the volume was produced with MATLAB R2024a and the Symbolic Math Toolbox; the Advanpix Multiprecision Computing Toolbox was used in the few places where extended-precision arithmetic was needed (these are flagged inline in the relevant études). A user running a different MATLAB release should expect *floating-point-equivalent* output, not byte-equivalent: the Toolbox's symbolic simplification rules occasionally rewrite long rational expressions, and the printed coefficients in Études 21.9--21.11 may differ in form but not in mathematical content.

For users without MATLAB, the Python and Julia implementations cover *every* computational étude in the book; the MATLAB scripts are a parallel reference rather than a strict prerequisite.

== The Make pipeline <appendix-software-make>

The repository ships with a single `Makefile` (≈3 300 lines, almost entirely chapter-by-chapter declarative pattern rules) that orchestrates the entire build.

#block(stroke: 0.8pt + rgb(20, 45, 110), radius: 3pt, inset: 10pt,
  fill: rgb(248, 250, 254))[
  *Phony targets.*
  - `make textbook` --- compile the manuscript into `textbook/build/DD-Computational-Etudes-2026.pdf`. Depends on every figure listed in the chapter dependency lines.
  - `make figures` --- regenerate every figure (currently aliased to `figures-python`, since the Python figures are the ones embedded in the book).
  - `make figures-python`, `make figures-matlab`, `make figures-julia` --- regenerate only one language's worth of figures.
  - `make all` --- everything: figures, textbook, teaching plan.
  - `make tplan` --- compile the supplementary teaching plan in `tplan/`.
  - `make clean` --- remove the textbook build output.
  - `make clean-figures` --- remove the rendered PDF figures.
  - `make clean-tplan` --- remove the teaching-plan build output.
  - `make clean-all` --- all three of the above, in sequence.
]

The interpreter executables are exposed as overridable Make variables so that a user with a non-default installation can point at the correct binaries:

```bash
make textbook                                    # default tools
make TYPST=/opt/typst/bin/typst textbook         # custom typst
make JULIA=/usr/local/bin/julia figures-julia    # custom julia
make PYTHON=python3.11 figures-python            # custom python
```

The output PDF lives at `$(OUT_DIR)/DD-Computational-Etudes-2026.pdf` with `OUT_DIR = textbook/build`. Both names are simple Make variables and can be overridden on the command line.

== Figure pipeline conventions <appendix-software-figures>

Every script in `codes/<language>/ch<NN>/` follows the same conventions; conformity makes the build pipeline maintainable and the cross-language comparison automatic.

- *Output format and location.* Each script writes a single PDF figure to `textbook/figures/ch<NN>/<language>/<basename>.pdf`. PDF (vector format throughout) gives crisp typesetting at any zoom level, which matters for the dense annotation style of many of the convergence and pseudospectrum figures.

- *Single figure per script.* Multi-panel figures are produced by Matplotlib's `subplots`, MATLAB's `tiledlayout`, and CairoMakie's `Figure` --- one composed PDF, one script.

- *Header docstring.* Every script begins with a short header naming the author, the chapter, the étude reference, and the URL of the repository. A representative example is `codes/python/ch07/cheb_matrix.py`.

- *Shared colour palette.* Three colours recur throughout the book: navy `rgb(20, 45, 110)`, sky `rgb(120, 150, 210)`, coral `rgb(255, 90, 50)`, and teal `rgb(20, 130, 130)`. Convergence and stability plots use navy for the *primary* method, coral for the *foil* against which it is compared, teal for an *intermediate* third method, and sky for *theoretical envelopes* drawn as dashed lines.

- *Three-language parallelism.* The three implementations of any étude carry the *same* variable names, the *same* algorithmic structure, and the *same* numerical parameters. The Python version is canonical; the MATLAB and Julia versions are translations that preserve every named quantity. Cross-language equivalence is *audited* in two of the études of @ch-linear-eigen (18.3, 18.5), where the printed integer counts of "trusted modes" agree to the bit across all three languages.

== The three-language convention <appendix-software-three-languages>

Why three languages? The honest answer is given in the preface: different communities have different preferences. Python is the *lingua franca* of contemporary scientific computing and the natural choice for readers from the data-science and machine-learning side; MATLAB remains the workhorse of engineering and applied mathematics, with a matrix-first syntax that makes spectral methods particularly natural; Julia combines MATLAB's readability with the performance of compiled languages. Pick the one you know; consult the other two when you need to verify a result.

The technical motivation is more interesting. Triple-language parallelism is a *form of code review*. A subtle bug in one language's implementation --- a sign error, an off-by-one in the FFT shift, a parity confusion in a recurrence --- is unlikely to recur in two independently written translations. When all three implementations of an étude agree to floating-point precision (as Étude 18.5 measures), the result is significantly more credible than any single-language implementation could be. When they disagree, the bug always turns out to be in exactly one of them, and triangulating to find it is straightforward.

Throughout the book this convention is treated as a soft *theorem*: any étude whose three implementations disagree at more than rounding-error level is treated as buggy and is debugged before going to print.

== Reproducibility checklist <appendix-software-checklist>

A self-contained check that the repository is correctly installed:

#block(stroke: 0.8pt + rgb(20, 45, 110), radius: 3pt, inset: 10pt,
  fill: rgb(248, 250, 254))[
  *From a fresh clone.*
  + `git clone https://github.com/dutykh/computational-etudes && cd computational-etudes`
  + Set up Python:  `python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt`
  + Set up Julia:  `julia --project=. -e 'using Pkg; Pkg.instantiate()'`
  + Test a single étude: `python codes/python/ch20/truncation_stalls.py`
    --- writes `textbook/figures/ch20/python/truncation_stalls.pdf` and prints no errors.
  + Regenerate every Python figure: `make figures-python`.
  + Build the textbook PDF: `make textbook`.

  *Expected wall-clock time on a 2024-vintage laptop:* roughly 90 s for `pip install`, 5 min for `Pkg.instantiate`, 30 s per figure-generating étude (longer for the 2D Navier--Stokes and KS études of @ch-fourier-pseudo), 2 min for `typst compile` of the textbook.
]

To regenerate exactly the printed PDF, run `make clean-all && make all` from a fresh checkout against the pinned environments. The author makes no warranty that the PDF will be byte-identical (Typst font rendering depends on the installed font cache, which is a per-machine artefact), but the figure content, the printed numbers, and the typeset prose are guaranteed reproducible.

When citing the book, please use the BibTeX entry on the repository's `README.md`. When citing a particular étude rather than the volume as a whole, please give both the chapter number and the étude index (for instance, "Étude 20.1 of *Computational Études*") so a reader can locate the underlying script unambiguously.
